<?php

$title = 'Edit User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php 
$form = $this->form;
?>
<fieldset>
    <?php
    $formContent = '';
    echo $this->form()->openTag($form);
    foreach ($form as $element)
        $formContent .= $this->formrow($element) . "<br/>"; //note the "BR"

    echo $formContent;
    echo $this->form()->closeTag();

    ?>
</fieldset>
<?php 
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('action', $this->url('admin/default', array('controller' => 'enterprise', 'action'=>'edit')) . '/' . $this->id );
?>
<a href='/admin/enterprise/index'>Back</a>