<strong>Module:</strong>        Admin &raquo;
<strong>Controller:</strong>    Enterprise &raquo;
<strong>Action:</strong>        Index
</br>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Enterprises</h3>
            </div>
            <div class="panel-body">
                <a href="<?php echo $this->url('admin/default', array('controller' => 'enterprise', 'action'=>'add'));?>">Add Enterprise</a>

                <?php if (isset($enterprises)) : ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Users</th>
                        <th>Social Media Presences</th>
                        <th>Date Created</th>
                        <th>Date last Updated</th>
                        <th></th>
                    </tr>
                    </thead>
                <?php foreach($enterprises as $enterprise): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $enterprise->getId(); ?></td>
                        <td><?php echo $enterprise->getName(); ?></td>
                        <td><list><?php
                        foreach ($enterprise->getUsers()->toArray() as $user)
                        {
                            echo($user->getDisplayname() . '</br>');
                        } 
                        ?></list></td>
                        <td><list><?php
                        foreach ($enterprise->getSocialMediaPresences()->toArray() as $presence)
                        {
                            echo($presence->getName() . '</br>');
                        }
                        ?></list></td>
                        <td><?php echo $enterprise->getCreated()->format('Y-m-d'); ?></td>
                        <td><?php echo $enterprise->getLastUpdated()->format('Y-m-d'); ?></td><td>
                            <a href="<?php echo ($this->url('admin/default', array('controller' => 'enterprise', 'action'=>'edit')) . '/' . $enterprise->getId() );?>">Edit</a> |
                            <a href="<?php echo ($this->url('admin/default', array('controller' => 'enterprise', 'action'=>'delete')) . '/' . $enterprise->getId() );?>">Delete</a>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>