<strong>Module:</strong>        Admin &raquo;
<strong>Controller:</strong>    Page &raquo;
<strong>Action:</strong>        Index
</br>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Pages</h3>
            </div>
            <div class="panel-body">
                <a href="<?php echo $this->url('admin/default', array('controller' => 'page', 'action'=>'add'));?>">Add Page</a>

                <?php if (isset($pages)) : ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Social Media Presence</th>
                        <th>SM Service ID</th>
                        <th>Date Created</th>
                        <th>Date last Updated</th>
                        <th></th>
                    </tr>
                    </thead>
                <?php foreach($pages as $page): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $page->getId(); ?></td>
                        <td><?php echo $page->getTitle(); ?></td>
                        <td><?php echo $page->getSocialMediaPresence()->getName(); ?></td>
                        <td><?php echo $page->getSocialMediaServiceId(); ?></td>
                        <td><?php echo $page->getCreated()->format('Y-m-d'); ?></td>
                        <td><?php echo $page->getLastUpdated()->format('Y-m-d'); ?></td><td>
                            <a href="<?php echo ($this->url('admin/default', array('controller' => 'page', 'action'=>'edit')) . '/' . $page->getId() );?>">Edit</a> |
                            <a href="<?php echo ($this->url('admin/default', array('controller' => 'page', 'action'=>'delete')) . '/' . $page->getId() );?>">Delete</a>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>