<strong>Module:</strong>        Admin &raquo;
<strong>Controller:</strong>    EditModel &raquo;
<strong>Action:</strong>        Index
</br>
<h3>Administrative options:</h3>
<body>
<?php // set of url_helpers that resolve to administrative views ?>
<?php echo('Select a model to admnistrate:');?></br>
<a href='/admin/access_token/index'>Access Tokens</a></br>
<a href='/admin/dimension/index'>Insight Dimensions</a></br>
<a href='/admin/enterprise/index'>Parent Enterprises</a></br>
<a href='/admin/page/index'>Pages</a></br>
<a href='/admin/page_dimension/index'>Page Dimensions</a></br>
<a href='/admin/post/index'>Posts</a></br>
<a href='/admin/post_dimension/index'>Post Dimensions</a></br>
<a href='/admin/post_type/index'>Post Types</a></br>
<a href='/admin/social_media_gateway/index'>Social Media Gateways</a></br>
<a href='/admin/social_media_presence/index'>Social Media Presences</a></br>
<a href='/admin/user/index'>Users</a></br>
</body>