<h3>Administrative options:</h3>
<body>
<?php // set of url_helpers that resolve to administrative views ?>
<?php echo('Select a model to administrate:');?></br>
<a href='/admin/AccessToken/index'>Access Tokens</a></br>
<a href='/admin/Dimension/index'>Insight Dimensions</a></br>
<a href='/admin/Enterprise/index'>Parent Enterprises</a></br>
<a href='/admin/Page/index'>Pages</a></br>
<a href='/admin/PageDimension/index'>Page Dimensions</a></br>
<a href='/admin/Post/index'>Posts</a></br>
<a href='/admin/PostDimension/index'>Post Dimensions</a></br>
<a href='/admin/PostType/index'>Post Types</a></br>
<a href='/admin/SocialMediaGateway/index'>Social Media Gateways</a></br>
<a href='/admin/SocialMediaPresence/index'>Social Media Presences</a></br>
<a href='/admin/User/index'>Users</a></br>
</body>