<strong>Module:</strong>        Application &raquo;
<strong>Controller:</strong>    Fetch &raquo;
<strong>Action:</strong>        index
</br>
<?php 
$title = 'Fetch';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<h3>Fetch pages for:</h3>
<a href='/application/fetch/user'>Current User</a></br>
<h3>Fetch insights for:</h3>
<a href='/application/fetch/post'>Post</a></br>
<a href='/application/fetch/page'>Page</a></br>