<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Post Dimensions</h3>
            </div>
            <div class="panel-body">
                <?php if (isset($postdimensions)) : ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Dimension</th>
                        <th>Value</th>
                        <th>Post</th>
                        <th>Date Created</th>
                        <th>Date last Updated</th>
                        <th></th>
                    </tr>
                    </thead>
                <?php foreach($postdimensions as $postdimension): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $postdimension->getId(); ?></td>
                        <td><?php echo $postdimension->getDimension(); ?></td>
                        <td><?php
                        foreach($postdimension->getValues() as $item)
                        {
                            foreach($item as $key=>$value)
                            {
                                if($key == 'default')
                                {
                                    echo($value);
                                }
                                else
                                {
                                    echo('[\'' . $key . '\':\'' . $value . '\']</br>');
                                }
                            }
                        }
                        ?></td>
                        <td><?php echo $postdimension->getPost()->getTitle(); ?></td>
                        <td><?php echo $postdimension->getCreated()->format('Y-m-d'); ?></td>
                        <td><?php echo $postdimension->getLastUpdated()->format('Y-m-d'); ?></td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>