<strong>Module:</strong>        Admin &raquo;
<strong>Controller:</strong>    Dimension &raquo;
<strong>Action:</strong>        Delete
</br>
<?php

$title = 'Delete Dimension';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
Are you sure you want to delete dimension <?php echo $user->getUserName(); ?>? <br/>
<form method="post">
  <input type="submit" value="Delete">
</form>