<strong>Module:</strong>        Admin &raquo;
<strong>Controller:</strong>    Post &raquo;
<strong>Action:</strong>        Index
</br>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Pages</h3>
            </div>
            <div class="panel-body">
                <?php if (isset($posts)) : ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Page</th>
                        <th>SM Service ID</th>
                        <th>Date Created</th>
                        <th>Date last Updated</th>
                        <th></th>
                    </tr>
                    </thead>
                <?php foreach($posts as $post): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $post->getId(); ?></td>
                        <td><?php echo $post->getTitle(); ?></td>
                        <td><?php echo $post->getPage()->getTitle(); ?></td>
                        <td><?php echo $post->getSocialMediaServiceId(); ?></td>
                        <td><?php echo $post->getCreated()->getTimestamp(); ?></td>
                        <td><?php echo $post->getLastUpdated()->getTimestamp(); ?></td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>