<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CBC '. $this->translate('Social Analytics Database'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="CBC"/>&nbsp;<?php echo $this->translate('Social Analytics Database') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php
                    echo $this->navigation('navigation')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav')
                        ->setPartial(array('partial/navbar.phtml', 'Application'));
                    ?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <!-- Test if the User is connected, but not for login or register -->
        <?php $routeName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')
               ->getMvcEvent()->getRouteMatch()->getMatchedRouteName(); //die($routeName);?>
        <?php $thisIsLogin = ($routeName === 'zfcuser/login');?>
        <?php $thisIsRegister = ($routeName === 'zfcuser/register'); ?>
        <?php if(!$this->zfcUserIdentity() && !$thisIsRegister && !$thisIsLogin ): ?>
            <!-- display the login form -->
            <?php echo $this->zfcUserLoginWidget(array('redirect'=>'application')); ?>
        <?php else: ?>
            <div class="container">
            	<?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0); ?>
                <?php echo $this->content; ?>
                <hr>
                <footer>
                    <p>&copy; 2005 - <?php echo date('Y') ?> CBC <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
            </div>
        <?php endif?> 
        <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>