<?php 
$title = 'Setup DB tables';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<h3>Generate initial fixture values</h3>
<a href='/application/setup/populate_dimension'>Populate Edge Dimension table</a></br>
<a href='/application/setup/initial_entries'>Insert default administrative records</a></br>
<a href='/application/setup/social_media'>Create default Facebook gateway records</a></br>
<a href='/application/setup/get_facebook_token'>Get Facebook token from FB OAuth2</a></br>