<strong>Module:</strong>        Application &raquo;
<strong>Controller:</strong>    Setup &raquo;
<strong>Action:</strong>        socialMedia
</br>
<?php
$title = 'Enter Social Media Presence Information';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php 
$form = $this->form;
?>
<fieldset>
    <?php
    $formContent = '';
    echo $this->form()->openTag($form);
    foreach ($form as $element)
        $formContent .= $this->formrow($element) . "<br/>"; //note the "BR"

    echo $formContent;
    echo $this->form()->closeTag();

    ?>
</fieldset>
<?php 
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('action', $this->url('application', array('controller' => 'setup', 'action'=>'social_media')) );
?>
<a href='/application/setup/index'>Back</a>