<strong>Module:</strong>        Admin &raquo;
<strong>Controller:</strong>    Access Token&raquo;
<strong>Action:</strong>        Index
</br>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Access Tokens</h3>
            </div>
            <div class="panel-body">
                <?php if (isset($tokens)) : ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Token</th>
                        <th>Social Media Gateway</th>
                        <th>Date Created</th>
                        <th>Date last Updated</th>
                        <th></th>
                    </tr>
                    </thead>
                <?php foreach($tokens as $token): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $token->getId(); ?></td>
                        <td><?php echo $token->getToken(); ?></td>
                        <td><?php if($token->getSocialMediaGateway()) echo $token->getSocialMediaGateway()->getName(); else echo '----';?></td>
                        <td><?php echo $token->getCreated()->format('Y-m-d'); ?></td>
                        <td><?php echo $token->getLastUpdated()->format('Y-m-d'); ?></td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>