<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'API\Module'                        => __DIR__ . '/Module.php',
    'API\Controller\SkeletonController' => __DIR__ . '/src/API/Controller/SkeletonController.php',
    'APITest\Framework\TestCase'        => __DIR__ . '/tests/API/Framework/TestCase.php',
    'APITest\SampleTest'                => __DIR__ . '/tests/API/SampleTest.php',
);
