<?php
    $this->headLink()->appendStylesheet('/css/fam-icons.css');
?>
<div class="container">
<h2>
	Home 
</h2>

<div class="row">
	<div class="span3">
		<a href="#"><i class="fam-cog"> </i> Cat é Categories </a> 
	</div> 
	<div class = "span9" > 
		Management of cat é Categories 
	</div> 
</div> 
<hr/>
	<div class = "row" > 
		<div class = "span3" >
			<a href = "#"> 
			<i class = "fam-page"> </i> Jobs </a> 
		</div> 
		<div class = "span9"> Management jobs 
		</div> 
	</div > 
<hr/> 
<div class = "row" > 
	<div class = "span3"> 
		<a href = "#"> 
		<i class = "fam-user" > </i> Users </a> </div> 
			<div class = "span9" > User Management 
			</div> 
		</div> 
</div>