<strong>Module:</strong>        Admin &raquo;
<strong>Controller:</strong>    Index &raquo;
<strong>Action:</strong>        index
</br>
<h3>Administrative options:</h3>
<body>
<?php // set of url_helpers that resolve to administrative views ?>
<?php echo('List of administrative options goes here');?></br>
<a href='/index/index/edit_model'>- edit model data</a></br>
<a href='/index/index/social_media'>- social media auth data</a></br>
<a href='/index/index/user_permission'>- administarate user permissions</a></br>
<a href='/index/index/user_edit'>- edit user data</a></br>
<a href='/index/index/generate_report'>- generate report</a></br>
</body>