<h3>Administrative options:</h3>
<body>
<?php // set of url_helpers that resolve to administrative views ?>
<?php echo('List of administrative options goes here');?></br>
<a href='/admin/editModel/index'>- edit model data</a></br>
<a href='/admin/index/socialMedia'>- social media auth data</a></br>
<a href='/admin/index/userPermission'>- administarate user permissions</a></br>
<a href='/admin/index/userEdit'>- edit user data</a></br>
<a href='/admin/index/generateReport'>- generate report</a></br>
</body>